### ISSUE TITLE
cuts to csv

### ISSUE THREAD

**Issue by dvxyz** [felixrupp/comskipCutsConverter#2]
Hi

any way to convert ts.cuts-files back to plaintext which could be used, for instance to cut the recording with ffmpeg?

I use comskip to detect commercials, fine-tune afterwards the cuts with cutlist-editor and cut the recording on the STB.

Following I encode the recordings to h264 and it would be great to be able to cut and encode in one step using ffmpeg.

**Comment by felixrupp** [comment]
Hi @dvxyz,

that’s possible yes, I actually read out the .cuts binary format in my code, see here: https://github.com/felixrupp/comskipCutsConverter/blob/f71759d943bb885adbf2f3d8a6b7c818a1c04764/src/Converter.php#L92

Regards,
Felix
